# This file was generated by GoReleaser. DO NOT EDIT.
class Dapper < Formula
  desc "PSPDFKit's maintained fork of Rancher's dapper"
  homepage "https://github.com/pspdfkit-ops/dapper"
  version "0.3.4-PSPDFKit-1.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pspdfkit-ops/dapper/releases/download/v0.3.4-PSPDFKit-1.6.0/dapper_0.3.4-PSPDFKit-1.6.0_darwin_amd64.tar.gz"
    sha256 "a4b16be61484479354bc0906da8837ee38c9627f00288bda763f6b1aabcad2ec"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pspdfkit-ops/dapper/releases/download/v0.3.4-PSPDFKit-1.6.0/dapper_0.3.4-PSPDFKit-1.6.0_linux_amd64.tar.gz"
      sha256 "cd0d9f63c4a9ec9a376f03970d3b0409e9e2b8a6f1dd9270a3a327fb8359d06e"
    end
  end

  def install
    bin.install "dapper"
  end

  test do
    system "#{bin}/dapper --version"
  end
end
